#!/bin/bash

[ -n "$SSH_CLIENT" ] && SESSION_TYPE="remote"

cat > /tmp/rpbcopy

if [[ $SESSION_TYPE == "remote" ]]; then
  cat /tmp/rpbcopy | nc -C 127.0.0.1 2224
else
  cat /tmp/rpbcopy | pbcopy
fi

cat /tmp/rpbcopy
